// NOTE: This diff was generated by running `diff -C0 lao tzu`
export const diff = `*** lao	2021-10-27 15:58:28.000000000 -0400
--- tzu	2021-10-27 15:58:22.000000000 -0400
***************
*** 1,2 ****
- The Way that can be told of is not the eternal Way;
- The name that can be named is not the eternal name.
--- 0 ----
***************
*** 4 ****
! The Named is the mother of all things.
--- 2,3 ----
! The named is the mother of all things.
! 
***************
*** 11 ****
--- 11,13 ----
+ They both may be called deep and profound.
+ Deeper and more profound,
+ The door of all subtleties!`;

export const lao = `The Way that can be told of is not the eternal Way;
The name that can be named is not the eternal name.
The Nameless is the origin of Heaven and Earth;
The Named is the mother of all things.
Therefore let there always be non-being,
  so we may see their subtlety,
And let there always be being,
  so we may see their outcome.
The two are the same,
But after they are produced,
  they have different names.`;

export const tzu = `The Nameless is the origin of Heaven and Earth;
The named is the mother of all things.

Therefore let there always be non-being,
  so we may see their subtlety,
And let there always be being,
  so we may see their outcome.
The two are the same,
But after they are produced,
  they have different names.
They both may be called deep and profound.
Deeper and more profound,
The door of all subtleties!`;
