name: 'Flag Untested Code'
description: "Flag lines that aren't covered by a corresponding jest test"
runs:
  using: 'composite'
  steps:
    - run: dist/index.js
      shell: bash
    - name: Create Comment
      uses: jungwinter/comment@v1
      id: create
      with:
        type: create
        body: "Hello, world"
        issue_number: ${{ github.event.number }}
        token: ${{ inputs.token }}
inputs:
  jest-bin:
    required: true
    description: 'Path to your jest library, probably node_modules/.bin/jest'
  custom-working-directory:
    required: false
    description: 'Path to your working directory, uses `.` if not provided'
  annotation-level:
    required: false
    description: "'warning' or 'failure', defaults to 'warning'"
  token:
    required: true
    description: 'Pass in secrets.GITHUB_TOKEN'
branding:
  icon: check-circle
  color: red
